export const DateFormatList = [
  { label: "DD-MM-YYYY", value: "dd-MM-yyyy" },
  { label: "DD/MM/YYYY", value: "dd/MM/yyyy" },
  { label: "DD.MM.YYYY", value: "dd.MM.yyyy" },
  { label: "DD MM YYYY", value: "dd MM yyyy" },
  { label: "DD-MM-YY", value: "dd-MM-yy" },
  { label: "DD/MM/YY", value: "dd/MM/yy" },
  { label: "DD.MM.YY", value: "dd.MM.yy" },
  { label: "D.MM.YY", value: "d.MM.yy" },
  { label: "D-M-YY", value: "d-M-yy" },
  { label: "D/M/YY", value: "d/M/yy" },
  { label: "D.M.YY", value: "d.M.yy" },
  { label: "D.M.YY.", value: "d.M.yy." },
  { label: "D-M-YYYY", value: "d-M-yyyy" },
  { label: "D/M/YYYY", value: "d/M/yyyy" },
  { label: "D.M.YYYY", value: "d.M.yyyy" },
  { label: "D. M. YYYY.", value: "d. M. yyyy." },
  { label: "D. M. YYYY", value: "d. M. yyyy" },
  { label: "D MMM, YYYY", value: "d MMM, yyyy" },
  { label: "DD MMM, YYYY", value: "dd MMM, yyyy" },
  { label: "D. MMMM YYYY", value: "d. MMMM yyyy" },
  { label: "DD.MM.YYYY.", value: "dd.MM.yyyy." },
  { label: "DD.MM.YY.", value: "dd.MM.yy." },
  { label: "YYYY-MM-DD", value: "yyyy-MM-dd" },
  { label: "YYYY/MM/DD", value: "yyyy/MM/dd" },
  { label: "YYYY.MM.DD", value: "yyyy.MM.dd" },
  { label: "YYYY MM DD", value: "yyyy MM dd" },
  { label: "YY/MM/DD", value: "yy/MM/dd" },
  { label: "YY-MM-DD", value: "yy-MM-dd" },
  { label: "YY.M.D", value: "yy.M.d" },
  { label: "YY-M-D", value: "yy-M-d" },
  { label: "YY. M. D", value: "yy. M. d" },
  { label: "YYYY/M/D", value: "yyyy/M/d" },
  { label: "YYYY.MM.DD.", value: "yyyy.MM.dd." },
  { label: "YYYY. MM. DD", value: "yyyy. MM. dd" },
  { label: "MM-DD-YYYY", value: "MM-dd-yyyy" },
  { label: "MM/DD/YYYY", value: "MM/dd/yyyy" },
  { label: "MM.DD.YYYY", value: "MM.dd.yyyy" },
  { label: "MM DD YYYY", value: "MM dd yyyy" },
  { label: "MM-DD-YY", value: "MM-dd-yy" },
  { label: "MM/DD/YY", value: "MM/dd/yy" },
  { label: "M/DD/YY", value: "M/dd/yy" },
  { label: "MMM-DD-YYYY", value: "MMM-dd-yyyy" },
  { label: "MMM DD, YYYY", value: "MMM dd, yyyy" },
  { label: "MMM D, YYYY", value: "MMM d, yyyy" },
  { label: "MMMM D, YYYY", value: "MMMM d, yyyy" },
  { label: "YYYY.DD.MM", value: "yyyy.dd.MM" },
  { label: "YY.D.M", value: "yy.d.M" },
];
